package com.myspace.restopsrecomms;

import com.myspace.restopsrecomms.RestaurantData;
import com.myspace.restopsrecomms.EmployeeRecommendation;

rule "recommend_staff_for_peak_time_slot"
    salience 75
    when
        $restaurant : RestaurantData(timeSlotExpectedSales > 4000)
        $recommendation : EmployeeRecommendation()
    then
        $recommendation.addRestaurantEmployees(2);
        $recommendation.addRuleExecuted(drools.getRule().getName());
        update($recommendation);
end