package com.myspace.restopsrecomms;

import com.myspace.restopsrecomms.RestaurantData;
import com.myspace.restopsrecomms.EmployeeRecommendation;

rule "recommend_staffing_based_on_sales_and_autoking"
    salience 90
    when
        $restaurant : RestaurantData(totalExpectedSales > 5000, hasAutoking == true)
        $recommendation : EmployeeRecommendation()
    then
        $recommendation.addRestaurantEmployees(2);
        $recommendation.addRuleExecuted(drools.getRule().getName());
        update($recommendation);
end