package com.myspace.restopsrecomms;

import com.myspace.restopsrecomms.RestaurantData;
import com.myspace.restopsrecomms.EmployeeRecommendation;

rule "recommend_extra_staff_for_large_restaurant"
    salience 80
    when
        $restaurant : RestaurantData(restaurantSize == "L")
        $recommendation : EmployeeRecommendation()
    then
        $recommendation.addRestaurantEmployees(3);
        $recommendation.addRuleExecuted(drools.getRule().getName());
        update($recommendation);
end