package com.capstonespace.resopsrecomms;
import java.util.Map;
import java.util.HashMap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeRecommendation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String calculationDateTime;
	private java.lang.Integer restaurantEmployees = 0;
	private java.lang.Integer restaurantExtraEmployees = 0;
	private java.lang.Integer homeDeliveryEmployees = 0;
	private java.util.Map<String, Integer> locationBreakdown = new java.util.HashMap();

	private java.lang.String companyId;

	private java.lang.String restaurantId;

	private java.util.List<java.lang.String> rulesExecuted = new java.util.ArrayList<>();

	public EmployeeRecommendation() {
	}

	public java.lang.String getCalculationDateTime() {
		return this.calculationDateTime;
	}

	public void setCalculationDateTime(java.lang.String calculationDateTime) {
		this.calculationDateTime = calculationDateTime;
	}

	public java.lang.Integer getRestaurantEmployees() {
		return this.restaurantEmployees;
	}

	public void setRestaurantEmployees(java.lang.Integer restaurantEmployees) {
		this.restaurantEmployees = restaurantEmployees;
	}

	public java.lang.Integer getRestaurantExtraEmployees() {
		return this.restaurantExtraEmployees;
	}

	public void setRestaurantExtraEmployees(
			java.lang.Integer restaurantExtraEmployees) {
		this.restaurantExtraEmployees = restaurantExtraEmployees;
	}

	public java.lang.Integer getHomeDeliveryEmployees() {
		return this.homeDeliveryEmployees;
	}

	public void setHomeDeliveryEmployees(java.lang.Integer homeDeliveryEmployees) {
		this.homeDeliveryEmployees = homeDeliveryEmployees;
	}

	public java.lang.String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(java.lang.String companyId) {
		this.companyId = companyId;
	}

	public java.lang.String getRestaurantId() {
		return this.restaurantId;
	}

	public Map<String, Integer> getLocationBreakdown() {
		return this.locationBreakdown;
	}

	public void setRestaurantId(java.lang.String restaurantId) {
		this.restaurantId = restaurantId;
	}

	public void addRestaurantEmployees(int restaurantEmployees) {
		this.restaurantEmployees += restaurantEmployees;
	}

	public void addRestaurantExtraEmployees(int restaurantExtraEmployees) {
		this.restaurantExtraEmployees += restaurantExtraEmployees;
	}

	public void addLocation(String key) {
		if (!locationBreakdown.containsKey(key)) {
			locationBreakdown.put(key, 1);
		} else {
			locationBreakdown.put(key, locationBreakdown.get(key) + 1);
		}
	}

	public java.util.List<java.lang.String> getRulesExecuted() {
		return this.rulesExecuted;
	}

	public void setRulesExecuted(java.util.List<java.lang.String> rulesExecuted) {
		this.rulesExecuted = rulesExecuted;
	}
	
	public void addRuleExecuted(String rule){
	    this.rulesExecuted.add(rule);
	}
	
	public boolean containsRuleExecuted(String rule){
	    return this.rulesExecuted.contains(rule);
	}

	public EmployeeRecommendation(java.lang.String calculationDateTime,
			java.lang.Integer restaurantEmployees,
			java.lang.Integer restaurantExtraEmployees,
			java.lang.Integer homeDeliveryEmployees,
			java.lang.String companyId, java.lang.String restaurantId,
			java.util.List<java.lang.String> rulesExecuted) {
		this.calculationDateTime = calculationDateTime;
		this.restaurantEmployees = restaurantEmployees;
		this.restaurantExtraEmployees = restaurantExtraEmployees;
		this.homeDeliveryEmployees = homeDeliveryEmployees;
		this.companyId = companyId;
		this.restaurantId = restaurantId;
		this.rulesExecuted = rulesExecuted;
	}

}