package com.capstonespace.resopsrecomms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestaurantData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String restaurantSize;
	private java.lang.Boolean hasAutoking;
	private double totalExpectedSales;
	private double timeSlotExpectedSales;
	private java.time.LocalDateTime calculationDateTime;
	private java.time.LocalDateTime openLocalDateTime;
	private java.time.LocalDateTime closeLocalDateTime;

	private java.lang.String companyId;

	private java.lang.String restaurantId;

	private double previousDaySales;

	private java.lang.String distanceHD;

	public RestaurantData() {
	}

	public java.lang.String getRestaurantSize() {
		return this.restaurantSize;
	}

	public void setRestaurantSize(java.lang.String restaurantSize) {
		this.restaurantSize = restaurantSize;
	}

	public java.lang.Boolean getHasAutoking() {
		return this.hasAutoking;
	}

	public void setHasAutoking(java.lang.Boolean hasAutoking) {
		this.hasAutoking = hasAutoking;
	}

	public double getTotalExpectedSales() {
		return this.totalExpectedSales;
	}

	public void setTotalExpectedSales(double totalExpectedSales) {
		this.totalExpectedSales = totalExpectedSales;
	}

	public double getTimeSlotExpectedSales() {
		return this.timeSlotExpectedSales;
	}

	public void setTimeSlotExpectedSales(double timeSlotExpectedSales) {
		this.timeSlotExpectedSales = timeSlotExpectedSales;
	}

	public void setPpreviousDaySales(double previousDaySales) {
		this.previousDaySales = previousDaySales;
	}

	public java.time.LocalDateTime getCalculationDateTime() {
		return this.calculationDateTime;
	}

	public void setCalculationDateTime(
			java.time.LocalDateTime calculationDateTime) {
		this.calculationDateTime = calculationDateTime;
	}

	public java.time.LocalDateTime getOpenLocalDateTime() {
		return this.openLocalDateTime;
	}

	public void setOpenLocalDateTime(java.time.LocalDateTime openLocalDateTime) {
		this.openLocalDateTime = openLocalDateTime;
	}

	public java.time.LocalDateTime getCloseLocalDateTime() {
		return this.closeLocalDateTime;
	}

	public void setCloseLocalDateTime(java.time.LocalDateTime closeLocalDateTime) {
		this.closeLocalDateTime = closeLocalDateTime;
	}

	public java.lang.String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(java.lang.String companyId) {
		this.companyId = companyId;
	}

	public java.lang.String getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(java.lang.String restaurantId) {
		this.restaurantId = restaurantId;
	}

	public double getPreviousDaySales() {
		return this.previousDaySales;
	}

	public void setPreviousDaySales(double previousDaySales) {
		this.previousDaySales = previousDaySales;
	}

	public java.lang.String getDistanceHD() {
		return this.distanceHD;
	}

	public void setDistanceHD(java.lang.String distanceHD) {
		this.distanceHD = distanceHD;
	}

	public RestaurantData(java.lang.String restaurantSize,
			java.lang.Boolean hasAutoking, double totalExpectedSales,
			double timeSlotExpectedSales,
			java.time.LocalDateTime calculationDateTime,
			java.time.LocalDateTime openLocalDateTime,
			java.time.LocalDateTime closeLocalDateTime,
			java.lang.String companyId, java.lang.String restaurantId,
			double previousDaySales, java.lang.String distanceHD) {
		this.restaurantSize = restaurantSize;
		this.hasAutoking = hasAutoking;
		this.totalExpectedSales = totalExpectedSales;
		this.timeSlotExpectedSales = timeSlotExpectedSales;
		this.calculationDateTime = calculationDateTime;
		this.openLocalDateTime = openLocalDateTime;
		this.closeLocalDateTime = closeLocalDateTime;
		this.companyId = companyId;
		this.restaurantId = restaurantId;
		this.previousDaySales = previousDaySales;
		this.distanceHD = distanceHD;
	}

}